# Generated by Django 4.1.2 on 2023-03-11 12:59

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_desciption_subclass_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'Abilities'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'verbose_name_plural': 'Sub classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='armor_proficiency',
            field=models.ManyToManyField(to='classes.armortype'),
        ),
        migrations.AddField(
            model_name='class',
            name='skills',
            field=models.ManyToManyField(to='classes.skill'),
        ),
        migrations.AddField(
            model_name='class',
            name='wepond_proficiency',
            field=models.ManyToManyField(to='classes.wepondtype'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='spell_slots',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]), null=True, size=9),
        ),
        migrations.AddField(
            model_name='class',
            name='tool_proficiency',
            field=models.ManyToManyField(to='classes.tooltype'),
        ),
    ]
