# Generated by Django 4.1.2 on 2023-03-11 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_wepond_proficiency_class_weapon_proficiency'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WepondType',
            new_name='WeaponType',
        ),
    ]
