# Generated by Django 4.1.2 on 2023-03-11 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_rename_wepondtype_weapontype'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_spesific_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
    ]
