# Generated by Django 4.1.1 on 2022-10-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_utility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='ritual',
            field=models.BooleanField(default=False),
        ),
    ]
