# Generated by Django 4.1.1 on 2022-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_alter_schoolsofmagic_options_alter_utility_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='origin_link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
