# Generated by Django 4.1.1 on 2022-10-04 15:26

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0003_utility_ritual'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='utilityLevel',
            field=models.IntegerField(choices=[(0, 'CANTRIP'), (1, 'FIRST'), (2, 'SECOND'), (3, 'THIRD'), (4, 'FOURTH'), (5, 'FIFTH'), (6, 'SIXTH'), (7, 'SEVENTH'), (8, 'EITGH'), (9, 'NINETH')], default=utils.UtilityLevel['FIRST']),
        ),
    ]
