# Generated by Django 4.1.1 on 2022-10-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_alter_utility_origin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='at_higher_levels',
            field=models.TextField(blank=True),
        ),
    ]
