# Generated by Django 4.1.1 on 2022-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0004_utility_utilitylevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='castingTime',
            field=models.CharField(blank=True, choices=[('Action', 'ACTION'), ('Bonus Action', 'BONUS_ACTION'), ('Hour', 'HOUR'), ('No Action', 'NO_ACTION'), ('Reaction', 'REACTION'), ('Spesial', 'SPESIAL')], max_length=15),
        ),
    ]
