# Generated by Django 4.1.1 on 2022-10-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0005_utility_castingtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='reactionCastingDescription',
            field=models.TextField(blank=True),
        ),
    ]
