# Generated by Django 4.1.1 on 2022-10-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_utility_reactioncastingdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='components',
            field=models.ManyToManyField(null=True, to='utilities.utilitycomponent'),
        ),
    ]
