# Generated by Django 4.1.1 on 2022-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_utility_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='materialComponents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='rangeDistance',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='utility',
            name='rangeType',
            field=models.CharField(blank=True, choices=[('None', 'NONE'), ('Self', 'SELF'), ('Toutch', 'TOUTCH'), ('Range', 'RANGED'), ('Sight', 'SIGHT'), ('Unlimited', 'UNLIMITED')], max_length=10),
        ),
    ]
