# Generated by Django 4.1.2 on 2022-10-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0007_utility_material_components'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
