# Generated by Django 4.1.1 on 2022-10-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_utility_materialcomponents_utility_rangedistance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='components',
            field=models.ManyToManyField(to='utilities.utilitycomponent'),
        ),
    ]
