# Generated by Django 4.1.2 on 2022-10-19 21:06

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_alter_utility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='description_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='utility',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='description_rendered'),
        ),
    ]
