# Generated by Django 4.1.1 on 2022-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_alter_utility_components'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='castingTime',
            new_name='castingTimeType',
        ),
        migrations.AddField(
            model_name='utility',
            name='casting_time_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='components',
            field=models.ManyToManyField(null=True, to='utilities.utilitycomponent'),
        ),
    ]
