# Generated by Django 4.1.2 on 2022-10-19 21:20

from django.db import migrations
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_utility_description_rendered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='description',
            field=markdownfield.models.MarkdownField(blank=True, rendered_field='description_rendered', use_editor=False),
        ),
    ]
