# Generated by Django 4.1.1 on 2022-10-23 18:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_alter_utility_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='at_higher_levels',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
