# Generated by Django 4.1.1 on 2022-10-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_rename_castingtime_utility_castingtimetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utility',
            old_name='castingTimeType',
            new_name='casting_time_type',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='materialComponents',
            new_name='material_components',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='rangeType',
            new_name='range_type',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='reactionCastingDescription',
            new_name='reaction_casting_description',
        ),
        migrations.RenameField(
            model_name='utility',
            old_name='utilityLevel',
            new_name='utility_level',
        ),
        migrations.RemoveField(
            model_name='utility',
            name='rangeDistance',
        ),
        migrations.AddField(
            model_name='utility',
            name='range_distance',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='components',
            field=models.ManyToManyField(blank=True, to='utilities.utilitycomponent'),
        ),
    ]
