# Generated by Django 4.1.1 on 2022-10-24 19:00

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_alter_utility_at_higher_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_field2', djrichtextfield.models.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='test',
            name='test_field',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='utility',
            name='at_higher_levels',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='utility',
            name='description',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
