# Generated by Django 4.1.1 on 2022-10-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0011_rename_castingtimetype_utility_casting_time_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='components',
        ),
        migrations.AlterField(
            model_name='utility',
            name='range_type',
            field=models.CharField(blank=True, choices=[('None', 'NONE'), ('Self', 'SELF'), ('Touch', 'TOUCH'), ('Range', 'RANGED'), ('Sight', 'SIGHT'), ('Unlimited', 'UNLIMITED')], max_length=10),
        ),
    ]
