# Generated by Django 4.1.1 on 2022-10-04 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_remove_utility_components_alter_utility_range_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityLevel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='utility',
            name='utility_level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='utilities.utilitylevel'),
        ),
    ]
