# Generated by Django 4.1.1 on 2022-10-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_utilitylevel_alter_utility_utility_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='utility_level',
        ),
    ]
