# Generated by Django 4.1.1 on 2022-10-04 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0014_remove_utility_utility_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utility',
            name='material_components',
        ),
        migrations.AddField(
            model_name='utility',
            name='utility_level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='utilities.utilitylevel'),
        ),
    ]
