# Generated by Django 4.1.1 on 2022-10-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_remove_utility_material_components_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityCastingTimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
