# Generated by Django 4.1.1 on 2022-10-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_rename_abbreviation_utilitycomponent_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='range_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.rangeunit'),
        ),
    ]
