# Generated by Django 4.1.1 on 2022-10-04 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0016_utilitycastingtimeunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='casting_time_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='utilities.utilitycastingtimeunit'),
        ),
    ]
