# Generated by Django 4.1.1 on 2022-10-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0018_remove_utility_casting_time_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DurationTimeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DurationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RangeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='utilitycastingtimeunit',
            old_name='name',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='utility',
            name='range_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.rangetype'),
        ),
    ]
