# Generated by Django 4.1.1 on 2022-10-04 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_durationtimeunit_durationtype_rangetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='components',
            field=models.ManyToManyField(blank=True, to='utilities.utilitycomponent'),
        ),
        migrations.AddField(
            model_name='utility',
            name='duration_time_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.durationtimeunit'),
        ),
        migrations.AddField(
            model_name='utility',
            name='duration_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.durationtype'),
        ),
    ]
