# Generated by Django 4.1.1 on 2022-10-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0020_utility_components_utility_duration_time_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='duration_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
