# Generated by Django 4.1.1 on 2023-03-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subclass',
            old_name='desciption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='class_feature',
            field=models.ManyToManyField(to='classes.feature'),
        ),
        migrations.AlterField(
            model_name='subclasslevel',
            name='class_feature',
            field=models.ManyToManyField(to='classes.feature'),
        ),
    ]
