# Generated by Django 4.1.2 on 2023-03-11 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_language_tooltype_alter_ability_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='wepond_proficiency',
            new_name='weapon_proficiency',
        ),
    ]
