# Generated by Django 4.1.2 on 2023-03-11 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_class_class_spesific_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevel',
            name='class_spesific',
        ),
        migrations.AddField(
            model_name='class',
            name='spell_slot_levels',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
            preserve_default=False,
        ),
    ]
