# Generated by Django 4.1.2 on 2023-03-11 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_remove_classlevel_class_spesific_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='class_spesific',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
    ]
