# Generated by Django 4.1.2 on 2023-03-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_classlevel_class_spesific'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sub_class_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='class_feature',
            field=models.ManyToManyField(blank=True, to='classes.feature'),
        ),
    ]
