# Generated by Django 4.1.2 on 2023-03-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0021_alter_utility_slug'),
        ('classes', '0010_class_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlevel',
            old_name='spell_slots',
            new_name='utiliy_slots',
        ),
        migrations.AddField(
            model_name='classlevel',
            name='class_utilities',
            field=models.ManyToManyField(blank=True, to='utilities.utility'),
        ),
    ]
