# Generated by Django 4.1.2 on 2023-03-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_rename_spell_slots_classlevel_utiliy_slots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='spell_slot_levels',
            new_name='utility_slot_levels',
        ),
    ]
