# Generated by Django 4.1.2 on 2023-03-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0012_rename_spell_slot_levels_class_utility_slot_levels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classlevel',
            old_name='utiliy_slots',
            new_name='utility_slots',
        ),
    ]
