# Generated by Django 4.1.1 on 2022-10-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolsOfMagic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityComponent',
            fields=[
                ('Abbreviation', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
