# Generated by Django 4.1.1 on 2022-10-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_durationtimeunit_durationtype_rangetype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolsofmagic',
            options={'verbose_name_plural': 'Schools of Magic'},
        ),
        migrations.AlterModelOptions(
            name='utility',
            options={'verbose_name_plural': 'Utilities'},
        ),
        migrations.AddField(
            model_name='utility',
            name='origin',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='utility',
            name='origin_link',
            field=models.URLField(null=True),
        ),
    ]
