# Generated by Django 4.1.2 on 2022-10-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0006_alter_utility_duration_time_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='material_components',
            field=models.TextField(blank=True),
        ),
    ]
