# Generated by Django 4.1.2 on 2022-10-20 22:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0008_rangeunit_utility_range_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
