# Generated by Django 4.1.1 on 2022-10-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_delete_test_delete_test2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
