# Generated by Django 4.1.1 on 2022-10-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0014_alter_utility_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitycomponent',
            old_name='Abbreviation',
            new_name='abbreviation',
        ),
        migrations.AddField(
            model_name='durationtimeunit',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rangeunit',
            name='abbreviation',
            field=models.CharField(default='ft', max_length=10),
            preserve_default=False,
        ),
    ]
