# Generated by Django 4.1.1 on 2022-10-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0016_alter_utility_range_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='casting_time_quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
