# Generated by Django 4.1.2 on 2023-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_alter_utility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
